#ifndef KITTYGG_H
#define KITTYGG_H

#include "Packets/DisconnectAck.h"
#include "Packets/Disconnecting.h"
#include "Packets/NotifyRemove.h"
#include "Packets/TypingNotify.h"
#include "Packets/LoginFailed.h"
#include "Packets/ListRequest.h"
#include "Packets/MessageRecv.h"
#include "Packets/MessageSend.h"
#include "Packets/NotifyFirst.h"
#include "Packets/NotifyReply.h"
#include "Packets/NotifyLast.h"
#include "Packets/MessageAck.h"
#include "Packets/MultiLogin.h"
#include "Packets/ListEmpty.h"
#include "Packets/ListReply.h"
#include "Packets/NewStatus.h"
#include "Packets/XmlAction.h"
#include "Packets/NotifyAdd.h"
#include "Packets/UserData.h"
#include "Packets/LoginOk.h"
#include "Packets/Welcome.h"
#include "Packets/Status.h"
#include "Packets/Login.h"
#include "Packets/Ping.h"
#include "Packets/Pong.h"

#endif // KITTYGG_H
